# Generated by Django 2.2.4 on 2019-08-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_reference', models.CharField(max_length=36)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Total Invoice Amount')),
                ('supplier_reference', models.CharField(max_length=36)),
                ('date_posted', models.DateField()),
            ],
        ),
    ]
